# Configuration Version, do not change!
Configuration Version: "1.0.5"

Default Waystone Name: "My Waystone"

# If you are using BungeeCord server, set this to true
# don't forget to use MySQL Storage type to make it work
# properly
Proxy Mode: false

# This option is to patch the issue with some servers that
# cannot handle to create more threads due to excessive CPU usage
# Use NativeScheduler for java scheduler behaviour
# Use BukkitScheduler for bukkit async scheduler with reentrant lock synchronization
# Use AsyncBukkitScheduler for bukkit async scheduler with no synchronization
# Use SyncBukkitScheduler for bukkit sync scheduler
Service Scheduler: "BukkitScheduler"
IO Service Scheduler: "BukkitScheduler"
Structure Service Scheduler: "BukkitScheduler"

Storage:
  # FILE or MYSQL
  Location: FILE
  # Block Storage is saved in local
  Block Directory: blocks
  Structure Directory: structures
  File:
    Waystone Directory: waystone_data
    Player Directory: player_data
    Names Directory: waystone_names
  MySQL:
    #Url: custom url here?
    Host: localhost
    Port: 3306
    Username: USERNAME HERE
    Password: PASSWORD HERE
    Database Name: DATABASE NAME HERE
    Table:
      Waystone: waystones
      Player: players
      Names: waystone_names
    Advanced:
      Minimum Idle: 5
      Maximum Pool Size: 50
      Connection Timeout: 10000
      Idle Timeout: 600000
      Max Lifetime: 1800000

# Prevents inappropriate words in waystone name
Blacklisted Names:
  - fuck
  - ass
  - shit
  - nigga
  - vagina
  - dick
  - penis
  - bitch
  - bastard
  - piss
  - damn
  - cunt
  - bollocks
  - bugger

Permissions:
  # Enable the permission to craft the items?
  Craft:
    # fancywaystones.craft.waystones.<environment>.<type>.<model>
    # example: fancywaystones.craft.waystones.THE_END.private.regular
    Waystones: false
    # fancywaystones.craft.deathbook
    Death Book: false
    # fancywaystones.craft.teleportationbook
    Teleportation Book: false
  # Enable the permission to use the items?
  Use:
    Waystones:
      # fancywaystones.craft.waystones.interact.<environment>.<type>.<model>
      # example: fancywaystones.craft.waystones.interact.THE_END.private.regular
      Interact: false
      # fancywaystones.craft.waystones.teleport.<environment>.<type>.<model>
      # example: fancywaystones.craft.waystones.teleport.THE_END.private.regular
      Teleport: false
    # fancywaystones.craft.deathbook
    Death Book: false
    # fancywaystones.craft.teleportationbook
    Teleportation Book: false

Waystone Inactivity:
  # If enabled, all waystones that are inactive, will be removed from the server
  Enable: false
  Duration: 40d
  # If this set to ONLINE_TIME_OWNER, the waystone inactivity will be determined by the waystone owner last online time
  # If this set to LAST_USED, the waystone inactivity will be determined by the last time player opened the waystone
  # If this set to LAST_VISITED, the waystone inactivity will be determined by the last time player visited the waystone
  # If this set to LAST_VISIT, the waystone inactivity will be determined by the last time player used the waystone to visit other waystone
  # If set otherwise, this purging system will be disabled
  Mode: ONLINE_TIME_OWNER
  # The check interval, it will only check loaded data.
  Check Interval: 1m

# Deprecated. See "item-model" in "models.yml"
# This is the default item for Waystone Item if its not
# specified inside models.yml
Waystone Item:
  Type: BREWING_STAND
  Display Name: "&e&lWAYSTONE"
  Flags:
    - HIDE_ATTRIBUTES
    - HIDE_POTION_EFFECTS
    - HIDE_ENCHANTS
    - HIDE_PLACED_ON
    - HIDE_DESTROYS
    - HIDE_UNBREAKABLE
  Lore:
    - "&7Place down the waystone              &7"
    - "&7to create a teleportation"
    - "&7point."
    - "&7"
    - "&7   Type: &d{waystone_type}"
    - "&7   Environment: &d{waystone_environment}"
    - "&7   Model: &d{waystone_model}"

Safe Teleport:
  Force If Fail: false
  # Add protection to the player when teleporting
  No Damage Time: 10s
  Check Radius: 4
  Check Height: 5

Economy:
  Level:
    Enable: true
    Currency Format: "{amount} levels"
  Vault:
    Enable: true
    Currency Format: "${amount}"
  Item:
    Enable: true
    Currency Format: "{amount}x {type}"
    Items:
      # To create ItemsAdder/MythicMobs/Oraxen item economy, use "Plugin" field and fill it with plugin name, and
      # use "Type" field to fill it with the specific item id
      # Example:
      # MyItemsAdderEconomy:
      #   Plugin: ItemsAdder
      #   Type: my_items_adder_item_id
      # MyOraxenEconomy:
      #   Plugin: Oraxen
      #   Type: oraxen_item_id
      # MyMythicMobsEconomy:
      #   Plugin: MythicMobs
      #   Type: mythic_mobs_id
      EnderPearl:
        Type: ENDER_PEARL
      Emerald:
        Type: EMERALD

Model:
  # Used by standard waystone model
  # for more model customization,
  # take a look at models.yml
  Active:
    server: DIAMOND_BLOCK
    public: GOLD_BLOCK
    region: IRON_BLOCK
    private: EMERALD_BLOCK
