name: "FancyWaystones"
main: thito.fancywaystones.FancyWaystones
api-version: 1.13
version: 1.0.20
author: Septogeddon
load: STARTUP
softdepend:
  - ProtocolLib
commands:
  fancywaystones:
    description: Waystone command
    permission: fancywaystones.admin
    aliases:
      - waystone
      - way
      - ws
      - fws
      - fw
permissions:
  fancywaystones.admin:
    description: Allows you to use Waystone command
    default: op